export enum CommandType {
  All = "all",
  Analise = "analise",
  Pokemons = "pokemons",
  PokemonInfo = "pokemon_info",
  Galeria = "galeria",
  Give = "give",
  Trade = "trade",
  Aceitar = "aceitar",
  Recusar = "recusar",
  Confirmar = "confirmar",
  Cancelar = "cancelar",
  Ajuda = "ajuda",
  UsageError = "usage_error",
  ForceSpawn = "forcespawn",
  Miru = "miru",
  Album = "album",
  Top = "top",
  Roll = "roll",
  Rolla = "rolla",
  Rollam = "rollam",
  Rollah = "rollah",
  MiruHelp = "miru_help",
}
